default:
  ALLOWED_HOSTS: ['*']
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .static
  DIRS_RESOURCES:
    - config
    - static
    - media
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/app/index/templates/
    - src/app/cart/templates/
    - src/project/templates/
  MODE_DEBUG: true
  HOST: ""
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: "Shoptms"
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000
  WEB_CONCURRENCY: 2
  SECRET_KEY: "1"


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2
  TEST_BROWSER: "firefox"

heroku:
  HOST: "My37.herokuapp.com"
  MODE_DEBUG: false
